
spring:
  application:
    name: springStudy1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: shardingSphere
#      active: dev #指定 环境配置
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yudada
#    username: root
#    password: 1234
    .data:
      redis:
        database: 1
        host: localhost
        port: 6379
        timeout: 5000
    aop:
      proxy-target-class: false
#decorator:
#  datasource:
#    p6spy:
#       日志格式
#      log-format: "\ntime:%(executionTime) || sql:%(sql)\n || Thread: %(threadName)\n"
#       自定义日志类
#      logging: custom
#      custom-appender-class: com.bolin.group1.log.StdoutLogger

logging:
  level:
    root: INFO  # 设置根日志级别为INFO
  file:
    name: logs/application.log  # 指定日志文件存储路径


server:
  address: 0.0.0.0
  port: 8080
