
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yudada
    username: root
    password: 1234
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
server:
  port: 8080
