
spring:
  main:
    allow-circular-references: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yudada_underscore
    username: root
    password: 1234
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
  aop:
    proxy-target-class: false
server:
  port: 8101
  address: 0.0.0.0
#decorator:
#  datasource:
#    p6spy:
#       日志格式
#      log-format: "\ntime:%(executionTime) || sql:%(sql)\n || Thread: %(threadName)\n"
#       自定义日志类
#      logging: custom
#      custom-appender-class: com.bolin.group1.log.StdoutLogger

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rocketmq:
  name-server: 127.0.0.1:9876  # RocketMQ NameServer 地址
  consumer:
    group:
#  producer:
#    group: my-producer-group   # 生产者的 group
#  consumer:
#    group: my-consumer-group2   # 消费者的 group


