mode:
  type: Standalone
dataSources:
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/yudada_2
    username: root
    password: 1234
  ds_3:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/yudada_3
    username: root
    password: 1234
rules:
  - !BROADCAST
    tables:
      - app
  - !SHARDING
    tables:
      logic_table:
        actualDataNodes: ds_${2..3}.user_answer_${0..1}
        tableStrategy:
          standard:
            shardingColumn: app_id
            shardingAlgorithmName: t_order_inline
    defaultDatabaseStrategy:
      standard:
        shardingColumn: tenant_id
        shardingAlgorithmName: database_inline
    defaultTableStrategy:
      none:
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${(tenant_id  % 2)+2}
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: user_answer_${app_id % 2}
props:
  sql-show: true



